# -*- coding: utf-8 -*-
"""AI_TOOL_DETECTION_(1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nJfyH67Sceab7QkrlfJVidflXr_GjE1H
"""

!pip install datasets

import kagglehub
import os
from datasets import load_dataset
from transformers import ViTImageProcessor, ViTForImageClassification, TrainingArguments, Trainer
from PIL import Image
import numpy as np
import torch
import transformers
import inspect

print("Transformers version:", transformers.__version__)
print("TrainingArguments module:", TrainingArguments.__module__)
print("TrainingArguments file:", inspect.getfile(TrainingArguments))
if transformers.__version__ < "4.11.0":
    raise ValueError("Please upgrade transformers to >= 4.11.0 using: pip install transformers==4.51.3")

path = kagglehub.dataset_download("salmaneunus/mechanical-tools-dataset")
print("Path to dataset files:", path)

print("Top-level directory contents:", os.listdir(path))

def find_class_subfolders(base_path):
    for subdir in os.listdir(base_path):
        subdir_path = os.path.join(base_path, subdir)
        if os.path.isdir(subdir_path):
            subsubdir_contents = [d for d in os.listdir(subdir_path) if os.path.isdir(os.path.join(subdir_path, d))]
            if subsubdir_contents:
                print(f"Found potential class subfolders in {subdir}:", subsubdir_contents)
                return subdir_path, subsubdir_contents
    return None, None

data_dir, class_labels = find_class_subfolders(path)
if data_dir and class_labels:
    print(f"Using data directory: {data_dir} with labels: {class_labels}")
else:
    print("No class subfolders found. Checking for metadata files...")
    metadata_files = [f for f in os.listdir(path) if f.endswith(('.csv', '.json', '.txt'))]
    if metadata_files:
        print("Found potential metadata files:", metadata_files)
        raise ValueError("Metadata file found. Please specify how to load labels from these files.")
    else:
        raise ValueError("No class subfolders or metadata files found. Please check dataset structure.")

try:
    # Load the 'train' split first
    dataset = load_dataset("imagefolder", data_dir=data_dir, split="train")
    # Create train and test splits from the 'train' split
    dataset = dataset.train_test_split(test_size=0.2, seed=42)
except Exception as e:
    print("Error loading dataset:", e)
    raise

print("Dataset features:", dataset["train"].features)
print("First example:", dataset["train"][0])

processor = ViTImageProcessor.from_pretrained("google/vit-base-patch16-224-in21k")

def preprocess(examples):
    images = [img.convert("RGB") if isinstance(img, Image.Image) else Image.open(img).convert("RGB") for img in examples["image"]]
    inputs = processor(images=images, return_tensors="pt", padding=True)
    examples["pixel_values"] = inputs["pixel_values"]
    return examples

dataset = dataset.map(preprocess, batched=True)

labels = dataset["train"].features["label"].names
print("Extracted labels:", labels)

model = ViTForImageClassification.from_pretrained(
    "google/vit-base-patch16-224-in21k",
    num_labels=len(labels),
    id2label={str(i): label for i, label in enumerate(labels)},
    label2id={label: str(i) for i, label in enumerate(labels)},
)

training_args = TrainingArguments(
    output_dir="./vit_tool_classifier",
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    num_train_epochs=3,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    push_to_hub=False,
    logging_dir="./logs",
    logging_steps=10,
    report_to="none",  # Disable W&B and other external logging
)

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    predictions = np.argmax(logits, axis=-1)
    accuracy = (predictions == labels).mean()
    return {"accuracy": accuracy}

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=dataset["train"],
    eval_dataset=dataset["test"],
    compute_metrics=compute_metrics,
)

trainer.train()

eval_results = trainer.evaluate()
print("Evaluation results:", eval_results)

trainer.save_model("./vit_tool_classifier_final")

from transformers import ViTImageProcessor, ViTForImageClassification
from torch.utils.data import DataLoader
import numpy as np
import torch
from sklearn.metrics import classification_report, confusion_matrix

processor = ViTImageProcessor.from_pretrained("google/vit-base-patch16-224-in21k")

model = ViTForImageClassification.from_pretrained("./vit_tool_classifier_final")
model.eval()

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)

import torch
import numpy as np
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, roc_curve, auc, precision_recall_curve, average_precision_score
from torch.utils.data import DataLoader
from itertools import cycle
import matplotlib.pyplot as plt

# Dataset & device
test_dataset = dataset["test"]

# Custom collate function
def custom_collate(batch):
    pixel_values = [item['pixel_values'] for item in batch]
    labels = [item['label'] for item in batch]
    pixel_values = [torch.tensor(pv) if not isinstance(pv, torch.Tensor) else pv for pv in pixel_values]
    pixel_values = torch.stack(pixel_values)
    labels = torch.tensor(labels)
    return {'pixel_values': pixel_values, 'label': labels}

test_loader = DataLoader(test_dataset, batch_size=16, shuffle=False, collate_fn=custom_collate)

# Evaluation
model.eval()
predictions, true_labels, probs = [], [], []

with torch.no_grad():
    for batch in test_loader:
        pixel_values = batch["pixel_values"].to(device)
        labels = batch["label"].to(device)
        outputs = model(pixel_values)
        logits = outputs.logits
        preds = logits.argmax(-1).cpu().numpy()
        prob = torch.nn.functional.softmax(logits, dim=-1).cpu().numpy()

        predictions.extend(preds)
        true_labels.extend(labels.cpu().numpy())
        probs.extend(prob)

# Convert to numpy
predictions = np.array(predictions)
true_labels = np.array(true_labels)
probs = np.array(probs)

# Unique classes
report_labels = np.unique(true_labels)

# Accuracy
accuracy = accuracy_score(true_labels, predictions)
print(f"\n🔹 Accuracy: {accuracy:.4f}")

# Classification Report
print("\n📄 Classification Report:")
print(classification_report(true_labels, predictions, target_names=[str(label) for label in report_labels]))

# Confusion Matrix
print("\n🧮 Confusion Matrix:")
cm = confusion_matrix(true_labels, predictions, labels=report_labels)
print(cm)

import torch
import numpy as np
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
from torch.utils.data import DataLoader
import matplotlib.pyplot as plt

# === Prepare test loader ===
test_dataset = dataset["test"]

def custom_collate(batch):
    pixel_values = [item['pixel_values'] for item in batch]
    labels = [item['label'] for item in batch]
    pixel_values = [torch.tensor(pv) if not isinstance(pv, torch.Tensor) else pv for pv in pixel_values]
    return {
        'pixel_values': torch.stack(pixel_values),
        'label': torch.tensor(labels),
    }

test_loader = DataLoader(test_dataset, batch_size=16, shuffle=False, collate_fn=custom_collate)

# === Run inference ===
model.eval()
all_preds, all_labels = [], []

with torch.no_grad():
    for batch in test_loader:
        x = batch["pixel_values"].to(device)
        y = batch["label"].to(device)
        out = model(x).logits
        preds = out.argmax(dim=-1)

        all_preds.extend(preds.cpu().numpy())
        all_labels.extend(y.cpu().numpy())

# Convert to numpy arrays
preds = np.array(all_preds)
true = np.array(all_labels)

# === Confusion matrix as image ===
cmat = confusion_matrix(true, preds, labels=np.unique(true))
disp = ConfusionMatrixDisplay(cmat, display_labels=[f"Class {i}" for i in np.unique(true)])
fig, ax = plt.subplots(figsize=(10, 10))
disp.plot(cmap='Blues', ax=ax, xticks_rotation=45)
ax.set_title("Confusion Matrix")
plt.tight_layout()
plt.show()

import matplotlib.cm as cm
import matplotlib.colors as mcolors

# Generate 15 unique colors using a colormap
cmap = cm.get_cmap('tab20', 15)  # 'tab20' or 'nipy_spectral' gives good variety

# ------------------------- ROC Curve -------------------------
plt.figure(figsize=(10, 8))

for i in range(len(report_labels)):
    fpr, tpr, _ = roc_curve(true_labels == report_labels[i], probs[:, report_labels[i]])
    roc_auc = auc(fpr, tpr)
    plt.plot(fpr, tpr, color=cmap(i), lw=2, label=f'Class {report_labels[i]} (AUC = {roc_auc:.2f})')

plt.plot([0, 1], [0, 1], 'k--', lw=2)
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curves for All Classes')
plt.legend(loc="lower right", bbox_to_anchor=(1.05, 0), borderaxespad=0.)
plt.grid(True)
plt.tight_layout()
plt.show()

# -------------------- Precision-Recall Curve --------------------
plt.figure(figsize=(10, 8))

for i in range(len(report_labels)):
    precision, recall, _ = precision_recall_curve(true_labels == report_labels[i], probs[:, report_labels[i]])
    avg_prec = average_precision_score(true_labels == report_labels[i], probs[:, report_labels[i]])
    plt.plot(recall, precision, color=cmap(i), lw=2, label=f'Class {report_labels[i]} (AP = {avg_prec:.2f})')

plt.xlabel('Recall')
plt.ylabel('Precision')
plt.title('Precision-Recall Curves for All Classes')
plt.legend(loc="lower left", bbox_to_anchor=(1.05, 0), borderaxespad=0.)
plt.grid(True)
plt.tight_layout()
plt.show()

# Step 6: Training vs Validation Loss Plot (Improved)
training_logs = trainer.state.log_history
# Get epochs where eval_loss is present
eval_epochs = [x['epoch'] for x in training_logs if 'eval_loss' in x]
# Get corresponding train_loss values for those epochs
# Modification: Get train loss for all epochs, then filter by eval_epochs
all_train_loss = [x['loss'] for x in training_logs if 'loss' in x]
train_loss_per_eval_epoch = [all_train_loss[int(epoch)-1] for epoch in eval_epochs]  # Use 'loss' for train loss
eval_loss = [x['eval_loss'] for x in training_logs if 'eval_loss' in x]

plt.figure(figsize=(8, 5))
# Plot using eval_epochs and train_loss_per_eval_epoch
plt.plot(eval_epochs, train_loss_per_eval_epoch, label='Training Loss')
plt.plot(eval_epochs, eval_loss, label='Validation Loss')
plt.xlabel("Epochs")
plt.ylabel("Loss")
plt.legend()
plt.title("Training vs Validation Loss")
plt.grid(True)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

def plot_classifier_misclassifier_comparison(cm, labels):
    """
    Generates a bar graph comparing classifier and misclassifier counts per class.

    Args:
        cm: Confusion matrix (numpy array).
        labels: List of class labels.
    """
    # Debugging: Print confusion matrix and labels

    print("Labels:", labels)

    # Ensure cm is square and labels match
    if cm.shape[0] != cm.shape[1] or len(labels) != cm.shape[0]:
        raise ValueError(f"Confusion matrix must be square and match labels length. "
                         f"Got cm shape {cm.shape} and {len(labels)} labels.")

    classifier_counts = np.diag(cm)
    misclassifier_counts = np.sum(cm, axis=0) - classifier_counts

    # Debugging: Print counts
    print("Classifier Counts:", classifier_counts)
    print("Misclassifier Counts:", misclassifier_counts)

    x = np.arange(len(labels))  # the label locations
    width = 0.35  # the width of the bars

    fig, ax = plt.subplots(figsize=(12, 6))

    # Plot bars
    rects1 = ax.bar(x - width/2, classifier_counts, width, label='Correct Classifications')
    rects2 = ax.bar(x + width/2, misclassifier_counts, width, label='Misclassifications')

    # Add labels, title, and ticks
    ax.set_ylabel('Counts')
    ax.set_title('Classifier vs. Misclassifier Counts per Class')
    ax.set_xticks(x)
    ax.set_xticklabels(labels, rotation=45, ha='right')
    ax.legend()

    # Add labels above each bar
    def autolabel(rects):
        for rect in rects:
            height = rect.get_height()
            ax.annotate('{}'.format(height),
                        xy=(rect.get_x() + rect.get_width() / 2, height),
                        xytext=(0, 3),  # 3 points vertical offset
                        textcoords="offset points",
                        ha='center', va='bottom')

    autolabel(rects1)
    autolabel(rects2)

    fig.tight_layout()
    plt.show()

# Sample confusion matrix for 3 classes
cm = np.array([
 [128,  12,   8],
 [17, 144,   8],
 [4,  11, 148]    # Class 2: 7 correct, 0 misclassified as Class 0, 1 as Class 1
])

# Example usage with consistent labels
labels = ["Class 0", "Class 1", "Class 2"]
plot_classifier_misclassifier_comparison(cm, labels)